version: '3.3'

services:
  php-cli:
    build: docker/php
    volumes:
      - $PWD/:/var/www/compound-calculator
      - $HOME/.composer:/tmp
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
    working_dir: /var/www/compound-calculator
    user: 1000:1000
    hostname: ${WEB_HOSTNAME-h2officedev}
